# Generated by Django 4.1.7 on 2023-03-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('bookname', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('meta', models.TextField(max_length=200)),
                ('publisher', models.CharField(default='Bookshub', max_length=40)),
                ('bookauthor', models.CharField(default='-', max_length=50)),
                ('isbn', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=15)),
                ('type', models.CharField(default='PDF', max_length=5)),
                ('thumbnail_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('download_url_one', models.URLField(blank=True, null=True)),
                ('download_url_two', models.URLField(blank=True, null=True)),
                ('time', models.DateField(auto_now=True)),
                ('content', models.TextField(max_length=300)),
            ],
        ),
    ]
