# Generated by Django 4.1.7 on 2023-03-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail_img',
        ),
    ]
